/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PortalIndexRouteImport } from './routes/portal.index'
import { Route as PortalTokenRouteImport } from './routes/portal.$token'
import { Route as DiagnosticoTokenRouteImport } from './routes/diagnostico.$token'
import { Route as AuthenticatedWhatsappRouteImport } from './routes/_authenticated/whatsapp'
import { Route as AuthenticatedVendasRouteImport } from './routes/_authenticated/vendas'
import { Route as AuthenticatedRelatoriosRouteImport } from './routes/_authenticated/relatorios'
import { Route as AuthenticatedPdvRouteImport } from './routes/_authenticated/pdv'
import { Route as AuthenticatedOrdensServicoRouteImport } from './routes/_authenticated/ordens-servico'
import { Route as AuthenticatedOrdensLixeiraRouteImport } from './routes/_authenticated/ordens-lixeira'
import { Route as AuthenticatedOrdensRouteImport } from './routes/_authenticated/ordens'
import { Route as AuthenticatedFinanceiroRouteImport } from './routes/_authenticated/financeiro'
import { Route as AuthenticatedEstoqueRouteImport } from './routes/_authenticated/estoque'
import { Route as AuthenticatedDiagnosticosRouteImport } from './routes/_authenticated/diagnosticos'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/_authenticated/configuracoes'
import { Route as AuthenticatedComprasRouteImport } from './routes/_authenticated/compras'
import { Route as AuthenticatedClientesRouteImport } from './routes/_authenticated/clientes'
import { Route as AuthenticatedComprasIdRouteImport } from './routes/_authenticated/compras.$id'
import { Route as ApiPublicWhatsappWebhookRouteImport } from './routes/api/public/whatsapp/webhook'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalIndexRoute = PortalIndexRouteImport.update({
  id: '/portal/',
  path: '/portal/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalTokenRoute = PortalTokenRouteImport.update({
  id: '/portal/$token',
  path: '/portal/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnosticoTokenRoute = DiagnosticoTokenRouteImport.update({
  id: '/diagnostico/$token',
  path: '/diagnostico/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWhatsappRoute = AuthenticatedWhatsappRouteImport.update({
  id: '/whatsapp',
  path: '/whatsapp',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVendasRoute = AuthenticatedVendasRouteImport.update({
  id: '/vendas',
  path: '/vendas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRelatoriosRoute = AuthenticatedRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPdvRoute = AuthenticatedPdvRouteImport.update({
  id: '/pdv',
  path: '/pdv',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOrdensServicoRoute =
  AuthenticatedOrdensServicoRouteImport.update({
    id: '/ordens-servico',
    path: '/ordens-servico',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOrdensLixeiraRoute =
  AuthenticatedOrdensLixeiraRouteImport.update({
    id: '/ordens-lixeira',
    path: '/ordens-lixeira',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOrdensRoute = AuthenticatedOrdensRouteImport.update({
  id: '/ordens',
  path: '/ordens',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFinanceiroRoute = AuthenticatedFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEstoqueRoute = AuthenticatedEstoqueRouteImport.update({
  id: '/estoque',
  path: '/estoque',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDiagnosticosRoute =
  AuthenticatedDiagnosticosRouteImport.update({
    id: '/diagnosticos',
    path: '/diagnosticos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedComprasRoute = AuthenticatedComprasRouteImport.update({
  id: '/compras',
  path: '/compras',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClientesRoute = AuthenticatedClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedComprasIdRoute = AuthenticatedComprasIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedComprasRoute,
} as any)
const ApiPublicWhatsappWebhookRoute =
  ApiPublicWhatsappWebhookRouteImport.update({
    id: '/api/public/whatsapp/webhook',
    path: '/api/public/whatsapp/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/clientes': typeof AuthenticatedClientesRoute
  '/compras': typeof AuthenticatedComprasRouteWithChildren
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/diagnosticos': typeof AuthenticatedDiagnosticosRoute
  '/estoque': typeof AuthenticatedEstoqueRoute
  '/financeiro': typeof AuthenticatedFinanceiroRoute
  '/ordens': typeof AuthenticatedOrdensRoute
  '/ordens-lixeira': typeof AuthenticatedOrdensLixeiraRoute
  '/ordens-servico': typeof AuthenticatedOrdensServicoRoute
  '/pdv': typeof AuthenticatedPdvRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/vendas': typeof AuthenticatedVendasRoute
  '/whatsapp': typeof AuthenticatedWhatsappRoute
  '/diagnostico/$token': typeof DiagnosticoTokenRoute
  '/portal/$token': typeof PortalTokenRoute
  '/portal/': typeof PortalIndexRoute
  '/compras/$id': typeof AuthenticatedComprasIdRoute
  '/api/public/whatsapp/webhook': typeof ApiPublicWhatsappWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/clientes': typeof AuthenticatedClientesRoute
  '/compras': typeof AuthenticatedComprasRouteWithChildren
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/diagnosticos': typeof AuthenticatedDiagnosticosRoute
  '/estoque': typeof AuthenticatedEstoqueRoute
  '/financeiro': typeof AuthenticatedFinanceiroRoute
  '/ordens': typeof AuthenticatedOrdensRoute
  '/ordens-lixeira': typeof AuthenticatedOrdensLixeiraRoute
  '/ordens-servico': typeof AuthenticatedOrdensServicoRoute
  '/pdv': typeof AuthenticatedPdvRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/vendas': typeof AuthenticatedVendasRoute
  '/whatsapp': typeof AuthenticatedWhatsappRoute
  '/diagnostico/$token': typeof DiagnosticoTokenRoute
  '/portal/$token': typeof PortalTokenRoute
  '/portal': typeof PortalIndexRoute
  '/compras/$id': typeof AuthenticatedComprasIdRoute
  '/api/public/whatsapp/webhook': typeof ApiPublicWhatsappWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/clientes': typeof AuthenticatedClientesRoute
  '/_authenticated/compras': typeof AuthenticatedComprasRouteWithChildren
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/diagnosticos': typeof AuthenticatedDiagnosticosRoute
  '/_authenticated/estoque': typeof AuthenticatedEstoqueRoute
  '/_authenticated/financeiro': typeof AuthenticatedFinanceiroRoute
  '/_authenticated/ordens': typeof AuthenticatedOrdensRoute
  '/_authenticated/ordens-lixeira': typeof AuthenticatedOrdensLixeiraRoute
  '/_authenticated/ordens-servico': typeof AuthenticatedOrdensServicoRoute
  '/_authenticated/pdv': typeof AuthenticatedPdvRoute
  '/_authenticated/relatorios': typeof AuthenticatedRelatoriosRoute
  '/_authenticated/vendas': typeof AuthenticatedVendasRoute
  '/_authenticated/whatsapp': typeof AuthenticatedWhatsappRoute
  '/diagnostico/$token': typeof DiagnosticoTokenRoute
  '/portal/$token': typeof PortalTokenRoute
  '/portal/': typeof PortalIndexRoute
  '/_authenticated/compras/$id': typeof AuthenticatedComprasIdRoute
  '/api/public/whatsapp/webhook': typeof ApiPublicWhatsappWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/clientes'
    | '/compras'
    | '/configuracoes'
    | '/dashboard'
    | '/diagnosticos'
    | '/estoque'
    | '/financeiro'
    | '/ordens'
    | '/ordens-lixeira'
    | '/ordens-servico'
    | '/pdv'
    | '/relatorios'
    | '/vendas'
    | '/whatsapp'
    | '/diagnostico/$token'
    | '/portal/$token'
    | '/portal/'
    | '/compras/$id'
    | '/api/public/whatsapp/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/clientes'
    | '/compras'
    | '/configuracoes'
    | '/dashboard'
    | '/diagnosticos'
    | '/estoque'
    | '/financeiro'
    | '/ordens'
    | '/ordens-lixeira'
    | '/ordens-servico'
    | '/pdv'
    | '/relatorios'
    | '/vendas'
    | '/whatsapp'
    | '/diagnostico/$token'
    | '/portal/$token'
    | '/portal'
    | '/compras/$id'
    | '/api/public/whatsapp/webhook'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/sitemap.xml'
    | '/_authenticated/clientes'
    | '/_authenticated/compras'
    | '/_authenticated/configuracoes'
    | '/_authenticated/dashboard'
    | '/_authenticated/diagnosticos'
    | '/_authenticated/estoque'
    | '/_authenticated/financeiro'
    | '/_authenticated/ordens'
    | '/_authenticated/ordens-lixeira'
    | '/_authenticated/ordens-servico'
    | '/_authenticated/pdv'
    | '/_authenticated/relatorios'
    | '/_authenticated/vendas'
    | '/_authenticated/whatsapp'
    | '/diagnostico/$token'
    | '/portal/$token'
    | '/portal/'
    | '/_authenticated/compras/$id'
    | '/api/public/whatsapp/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  DiagnosticoTokenRoute: typeof DiagnosticoTokenRoute
  PortalTokenRoute: typeof PortalTokenRoute
  PortalIndexRoute: typeof PortalIndexRoute
  ApiPublicWhatsappWebhookRoute: typeof ApiPublicWhatsappWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/': {
      id: '/portal/'
      path: '/portal'
      fullPath: '/portal/'
      preLoaderRoute: typeof PortalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/$token': {
      id: '/portal/$token'
      path: '/portal/$token'
      fullPath: '/portal/$token'
      preLoaderRoute: typeof PortalTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnostico/$token': {
      id: '/diagnostico/$token'
      path: '/diagnostico/$token'
      fullPath: '/diagnostico/$token'
      preLoaderRoute: typeof DiagnosticoTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/whatsapp': {
      id: '/_authenticated/whatsapp'
      path: '/whatsapp'
      fullPath: '/whatsapp'
      preLoaderRoute: typeof AuthenticatedWhatsappRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vendas': {
      id: '/_authenticated/vendas'
      path: '/vendas'
      fullPath: '/vendas'
      preLoaderRoute: typeof AuthenticatedVendasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/relatorios': {
      id: '/_authenticated/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof AuthenticatedRelatoriosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pdv': {
      id: '/_authenticated/pdv'
      path: '/pdv'
      fullPath: '/pdv'
      preLoaderRoute: typeof AuthenticatedPdvRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ordens-servico': {
      id: '/_authenticated/ordens-servico'
      path: '/ordens-servico'
      fullPath: '/ordens-servico'
      preLoaderRoute: typeof AuthenticatedOrdensServicoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ordens-lixeira': {
      id: '/_authenticated/ordens-lixeira'
      path: '/ordens-lixeira'
      fullPath: '/ordens-lixeira'
      preLoaderRoute: typeof AuthenticatedOrdensLixeiraRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ordens': {
      id: '/_authenticated/ordens'
      path: '/ordens'
      fullPath: '/ordens'
      preLoaderRoute: typeof AuthenticatedOrdensRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/financeiro': {
      id: '/_authenticated/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof AuthenticatedFinanceiroRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/estoque': {
      id: '/_authenticated/estoque'
      path: '/estoque'
      fullPath: '/estoque'
      preLoaderRoute: typeof AuthenticatedEstoqueRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/diagnosticos': {
      id: '/_authenticated/diagnosticos'
      path: '/diagnosticos'
      fullPath: '/diagnosticos'
      preLoaderRoute: typeof AuthenticatedDiagnosticosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/compras': {
      id: '/_authenticated/compras'
      path: '/compras'
      fullPath: '/compras'
      preLoaderRoute: typeof AuthenticatedComprasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clientes': {
      id: '/_authenticated/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof AuthenticatedClientesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/compras/$id': {
      id: '/_authenticated/compras/$id'
      path: '/$id'
      fullPath: '/compras/$id'
      preLoaderRoute: typeof AuthenticatedComprasIdRouteImport
      parentRoute: typeof AuthenticatedComprasRoute
    }
    '/api/public/whatsapp/webhook': {
      id: '/api/public/whatsapp/webhook'
      path: '/api/public/whatsapp/webhook'
      fullPath: '/api/public/whatsapp/webhook'
      preLoaderRoute: typeof ApiPublicWhatsappWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedComprasRouteChildren {
  AuthenticatedComprasIdRoute: typeof AuthenticatedComprasIdRoute
}

const AuthenticatedComprasRouteChildren: AuthenticatedComprasRouteChildren = {
  AuthenticatedComprasIdRoute: AuthenticatedComprasIdRoute,
}

const AuthenticatedComprasRouteWithChildren =
  AuthenticatedComprasRoute._addFileChildren(AuthenticatedComprasRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedClientesRoute: typeof AuthenticatedClientesRoute
  AuthenticatedComprasRoute: typeof AuthenticatedComprasRouteWithChildren
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDiagnosticosRoute: typeof AuthenticatedDiagnosticosRoute
  AuthenticatedEstoqueRoute: typeof AuthenticatedEstoqueRoute
  AuthenticatedFinanceiroRoute: typeof AuthenticatedFinanceiroRoute
  AuthenticatedOrdensRoute: typeof AuthenticatedOrdensRoute
  AuthenticatedOrdensLixeiraRoute: typeof AuthenticatedOrdensLixeiraRoute
  AuthenticatedOrdensServicoRoute: typeof AuthenticatedOrdensServicoRoute
  AuthenticatedPdvRoute: typeof AuthenticatedPdvRoute
  AuthenticatedRelatoriosRoute: typeof AuthenticatedRelatoriosRoute
  AuthenticatedVendasRoute: typeof AuthenticatedVendasRoute
  AuthenticatedWhatsappRoute: typeof AuthenticatedWhatsappRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedClientesRoute: AuthenticatedClientesRoute,
  AuthenticatedComprasRoute: AuthenticatedComprasRouteWithChildren,
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDiagnosticosRoute: AuthenticatedDiagnosticosRoute,
  AuthenticatedEstoqueRoute: AuthenticatedEstoqueRoute,
  AuthenticatedFinanceiroRoute: AuthenticatedFinanceiroRoute,
  AuthenticatedOrdensRoute: AuthenticatedOrdensRoute,
  AuthenticatedOrdensLixeiraRoute: AuthenticatedOrdensLixeiraRoute,
  AuthenticatedOrdensServicoRoute: AuthenticatedOrdensServicoRoute,
  AuthenticatedPdvRoute: AuthenticatedPdvRoute,
  AuthenticatedRelatoriosRoute: AuthenticatedRelatoriosRoute,
  AuthenticatedVendasRoute: AuthenticatedVendasRoute,
  AuthenticatedWhatsappRoute: AuthenticatedWhatsappRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  DiagnosticoTokenRoute: DiagnosticoTokenRoute,
  PortalTokenRoute: PortalTokenRoute,
  PortalIndexRoute: PortalIndexRoute,
  ApiPublicWhatsappWebhookRoute: ApiPublicWhatsappWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
